#!/usr/bin/env python3
"""
CivicFix AI Pipeline - Held-Out Test Set Evaluation
----------------------------------------------------
Evaluates the trained YOLO segmentation model on the held-out test split.

Produces all required artifacts:
  model_metrics.json      – Full evaluation metrics (precision, recall, mAP50,
                            mAP50-95, per-class, confusion matrix path, curve paths)
  class_mapping.json      – {class_id: class_name} mapping used during training
  [evaluation plots]      – F1_curve.png, PR_curve.png, confusion_matrix.png
                            (generated by Ultralytics model.val() automatically)

DISCLAIMER printed at every run:
  Metrics are computed on the HELD-OUT test split only.
  The model is NOT claimed to be "production-ready", "perfect", or "100% accurate".
  It is validated for educational and hackathon demonstration purposes only.

Usage:
  python evaluate_model.py                                # auto-detect paths
  python evaluate_model.py --weights best.pt --yaml data.yaml --output ./eval_out
"""

import os
import sys
import json
import datetime
import argparse
from pathlib import Path

CLASS_NAMES   = {0: "pothole", 1: "road_crack", 2: "manhole"}
MODEL_VERSION = "v1"

# Default path resolution (Kaggle → local fallback)
DEFAULT_WEIGHTS = [
    Path("/kaggle/working/civicfix_runs/civicfix_road_damage_seg_v1/weights/best.pt"),
    Path("data/processed/civicfix_runs/civicfix_road_damage_seg_v1/weights/best.pt"),
]
DEFAULT_YAML = [
    Path("/kaggle/working/civicfix_road_damage/data.yaml"),
    Path("data/processed/civicfix_road_damage/data.yaml"),
    Path("scripts/ai_pipeline/data.yaml"),
]


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def resolve_first(candidates: list[Path]) -> Path | None:
    for p in candidates:
        if p.exists():
            return p
    return None


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def evaluate_test_split(
    weights_path: Path,
    data_yaml_path: Path,
    output_dir: Path | None = None,
    batch: int = 4,
):
    """
    Run model.val() on the test split and write model_metrics.json
    and class_mapping.json to output_dir.

    Returns the evaluation report dict.
    """
    print("=" * 50)
    print("CIVICFIX MODEL TEST SET EVALUATION")
    print(f"Weights:    {weights_path}")
    print(f"Data YAML:  {data_yaml_path}")
    print("=" * 50)

    # ── DISCLAIMER ───────────────────────────────────────────────────────────
    print(
        "\n[DISCLAIMER] Evaluation metrics are derived from the HELD-OUT test split.\n"
        "  The model makes NO claim of being 'perfect', '100% accurate', or\n"
        "  'production-ready'. It is validated for educational/hackathon use only.\n"
        "  Unsupported visual categories (streetlights, water leakage, fallen trees,\n"
        "  blocked drains, garbage bins, illegal dumping) are NOT recognised by this\n"
        "  model. Images in those categories must be routed to authority review.\n"
    )

    try:
        from ultralytics import YOLO  # type: ignore
    except ImportError:
        print("[FAIL] Ultralytics is not installed. Run: pip install ultralytics")
        sys.exit(1)

    if not weights_path.exists():
        print(f"[FAIL] Weights file not found: {weights_path}")
        sys.exit(1)

    if not data_yaml_path.exists():
        print(f"[FAIL] data.yaml not found: {data_yaml_path}")
        sys.exit(1)

    if output_dir is None:
        output_dir = weights_path.parent
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Load model & detect framework version ────────────────────────────────
    model = YOLO(str(weights_path))

    try:
        import ultralytics
        framework_version = f"ultralytics=={ultralytics.__version__}"
    except Exception:
        framework_version = "ultralytics (version unknown)"

    try:
        import torch
        training_device = (
            f"cuda:{torch.cuda.current_device()} "
            f"({torch.cuda.get_device_name()})"
            if torch.cuda.is_available() else "cpu"
        )
    except Exception:
        training_device = "unknown"

    # ── Run evaluation on held-out test split ────────────────────────────────
    print("\n---> Running evaluation on held-out test split…")
    metrics = model.val(
        data=str(data_yaml_path),
        split="test",
        imgsz=640,
        batch=batch,
        plots=True,
        save_json=False,
    )

    # ── Extract aggregate segmentation metrics ───────────────────────────────
    seg = metrics.seg

    def safe_float(arr_or_val, default=0.0) -> float:
        try:
            import numpy as np  # type: ignore
            val = arr_or_val
            if hasattr(val, "mean"):
                val = float(val.mean())
            return round(float(val), 6)
        except Exception:
            return default

    seg_precision = safe_float(getattr(seg, "p",    0.0))
    seg_recall    = safe_float(getattr(seg, "r",    0.0))
    seg_map50     = safe_float(getattr(seg, "map50", 0.0))
    seg_map50_95  = safe_float(getattr(seg, "map",   0.0))

    # ── Per-class metrics ────────────────────────────────────────────────────
    per_class: dict[str, dict] = {}

    # p, r are arrays of shape [num_classes]
    p_arr  = getattr(seg, "p",    None)
    r_arr  = getattr(seg, "r",    None)
    ap_arr = getattr(seg, "maps", None)   # per-class mAP50-95

    for cls_id, cls_name in CLASS_NAMES.items():
        entry: dict = {}
        try:
            import numpy as np  # type: ignore
            if p_arr is not None and cls_id < len(p_arr):
                entry["precision"] = round(float(p_arr[cls_id]), 6)
            if r_arr is not None and cls_id < len(r_arr):
                entry["recall"] = round(float(r_arr[cls_id]), 6)
            if ap_arr is not None and cls_id < len(ap_arr):
                entry["mAP50_95"] = round(float(ap_arr[cls_id]), 6)
        except Exception:
            pass
        per_class[cls_name] = entry

    # ── Locate generated plot files (relative to save_dir) ───────────────────
    save_dir = Path(metrics.save_dir) if hasattr(metrics, "save_dir") else output_dir

    def find_plot(name: str) -> str:
        p = save_dir / name
        return str(p) if p.exists() else ""

    confusion_matrix_path = find_plot("confusion_matrix.png")
    f1_curve_path         = find_plot("F1_curve.png")
    pr_curve_path         = find_plot("PR_curve.png")

    # ── Retrieve training args from model (if available) ─────────────────────
    training_params: dict = {}
    try:
        args_yaml = weights_path.parent.parent / "args.yaml"
        if args_yaml.exists():
            import yaml  # type: ignore
            with open(args_yaml) as f:
                training_params = yaml.safe_load(f) or {}
    except Exception:
        pass

    # ── Assemble report ───────────────────────────────────────────────────────
    evaluation_report = {
        "model_name":      "civicfix_road_damage_segmentation",
        "model_version":   MODEL_VERSION,
        "task_type":       "image_segmentation",
        "framework":       framework_version,
        "training_device": training_device,
        "evaluation_split": "test",
        "evaluated_at":    datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "weights_path":    str(weights_path),
        "data_yaml_path":  str(data_yaml_path),
        "disclaimer": (
            "Metrics are computed on the held-out test split only. "
            "This model is NOT 'production-ready' or '100% accurate'. "
            "Educational/hackathon demonstration use only."
        ),
        "supported_classes": list(CLASS_NAMES.values()),
        "unsupported_categories_note": (
            "The following categories are NOT supported by this model and must be "
            "routed to authority review: broken streetlights, water leakage, "
            "blocked drains, fallen trees, overflowing garbage bins, illegal dumping."
        ),
        "metrics": {
            "precision":  seg_precision,
            "recall":     seg_recall,
            "mAP50":      seg_map50,
            "mAP50_95":   seg_map50_95,
        },
        "per_class_metrics":   per_class,
        "plot_artifacts": {
            "confusion_matrix": confusion_matrix_path,
            "f1_curve":         f1_curve_path,
            "pr_curve":         pr_curve_path,
        },
        "training_parameters": training_params,
    }

    # ── Write model_metrics.json ──────────────────────────────────────────────
    metrics_path = output_dir / "model_metrics.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(evaluation_report, f, indent=2)
    print(f"\n[OK] model_metrics.json → {metrics_path}")

    # ── Write class_mapping.json ──────────────────────────────────────────────
    class_mapping = {str(k): v for k, v in CLASS_NAMES.items()}
    cm_path = output_dir / "class_mapping.json"
    with open(cm_path, "w", encoding="utf-8") as f:
        json.dump(class_mapping, f, indent=2)
    print(f"[OK] class_mapping.json  → {cm_path}")

    # ── Console summary ───────────────────────────────────────────────────────
    print("\n--- Test Metric Summary ---")
    print(f"Precision:  {seg_precision:.4f}")
    print(f"Recall:     {seg_recall:.4f}")
    print(f"mAP50:      {seg_map50:.4f}")
    print(f"mAP50-95:   {seg_map50_95:.4f}")
    print("\nPer-class breakdown:")
    for cls_name, cls_m in per_class.items():
        print(f"  {cls_name}: {cls_m}")
    if confusion_matrix_path:
        print(f"\nConfusion matrix → {confusion_matrix_path}")
    if f1_curve_path:
        print(f"F1 curve         → {f1_curve_path}")
    if pr_curve_path:
        print(f"PR curve         → {pr_curve_path}")

    return evaluation_report


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="CivicFix model evaluation on held-out test split."
    )
    parser.add_argument(
        "--weights", "-w",
        help="Path to best.pt weights file (auto-detected if omitted).",
    )
    parser.add_argument(
        "--yaml", "-y",
        help="Path to data.yaml (auto-detected if omitted).",
    )
    parser.add_argument(
        "--output", "-o",
        help="Directory for output artifacts (defaults to weights parent dir).",
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=4,
        help="Batch size for evaluation (default: 4).",
    )
    args = parser.parse_args()

    weights  = Path(args.weights) if args.weights else resolve_first(DEFAULT_WEIGHTS)
    yaml_p   = Path(args.yaml)    if args.yaml    else resolve_first(DEFAULT_YAML)
    out_dir  = Path(args.output)  if args.output  else None

    if weights is None:
        print("[FAIL] Weights file not found. Use --weights.")
        sys.exit(1)
    if yaml_p is None:
        print("[FAIL] data.yaml not found. Use --yaml.")
        sys.exit(1)

    evaluate_test_split(weights, yaml_p, output_dir=out_dir, batch=args.batch)


if __name__ == "__main__":
    main()
